name: Reddit Scraper

on:
  schedule:
    # This will run the workflow every Friday at 9 AM PST (5 PM UTC)
    - cron: "0 17 * * 5"
  workflow_dispatch: # Allow manual triggers for testing

jobs:
  scraper:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # You can change this to your preferred version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install praw requests  # Install PRAW and requests directly

      # Run the scraper script
      - name: Run Reddit scraper
        env:
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          python fetchTop10Anime.py 
